name: Run ts-node

on: 
  schedule:
    - cron: '0 */4 * * *'  # Runs at midnight and noon
  workflow_dispatch: {}  # Allows manual triggering

jobs:
  run-ts-node:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Set timeout to 1 hour
    steps:
      - uses: actions/checkout@v4

      - name: Download secret value
        run: echo '${{ secrets.CRED_JSON }}' > creds.json

      - name: Install dependencies
        run: |
          npm install
          
      - run: npm start
